name: Dart

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Get Flutter
        uses: flutter-actions/setup-flutter@v2.3
        with:
          version: 3.19.0

      - name: Install dependencies
        run: flutter pub get

      - name: Compile Server
        run: dart compile exe server/server.dart

      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          allowUpdates: true
          artifact: server/server.exe
          makeLatest: true
          tag: Alpha
